### ISSUE TITLE
Make useful use of feedback message

### ISSUE THREAD

**Issue by xdrawks** [CS2103AUG2016-W10-C4/main#124]
When a panel is opened, such as error message or help window, it might be a good idea to display an instruction to close the panel in the feedback view

**Comment by ZhangYiJiang** [comment]
I think we can actually get rid of the feedback message for most commands when #136 and #109 lands, since most commands would involve some change that's visible on the task list, having a message on the feedback panel would be doing double work and is actually kind of distracting. The only commands that need to use this would be `save`, `load`, `undo` and `redo` I think
